<?php

return [
    'handle' => 'dryucelpolat',
    'profile_url' => 'https://www.instagram.com/dryucelpolat/',
    'posts' => [
        ['slug' => 'C6GJ3Smiud9', 'ext' => 'webp', 'alt' => 'Istinye Üniversitesi Liv Hastanesi'],
        ['slug' => 'C5Sxp-5CHyf', 'ext' => 'webp', 'alt' => 'Liv Hospital — operasyon'],
        ['slug' => 'C40cHsLiFnJ', 'ext' => 'webp', 'alt' => 'Liv Hospital'],
        ['slug' => 'C4gADt9CUEE', 'ext' => 'webp', 'alt' => 'Klinikten anlar'],
        ['slug' => 'C4LOw5Cingc', 'ext' => 'webp', 'alt' => 'Hasta takibi'],
        ['slug' => 'C4IlJbHC37L', 'ext' => 'webp', 'alt' => 'Operasyon anı'],
        ['slug' => 'C4GHCrri5Xt', 'ext' => 'webp', 'alt' => 'Liv Hospital Bahçeşehir'],
        ['slug' => 'C35JmKdiXKQ', 'ext' => 'jpg',  'alt' => 'Shockwave IVL — damar tıkanıklığı', 'is_reel' => true],
        ['slug' => 'C3TAtSAN7kJ', 'ext' => 'webp', 'alt' => 'Klinikten'],
        ['slug' => 'C29un5NClKy', 'ext' => 'webp', 'alt' => 'Liv Hospital'],
        ['slug' => 'C2223IWLQl5', 'ext' => 'webp', 'alt' => 'Hasta hikayesi'],
        ['slug' => 'C2mnXPzC-6g', 'ext' => 'webp', 'alt' => 'Kongre / etkinlik'],
        ['slug' => 'C2ABjsUiRmY', 'ext' => 'webp', 'alt' => 'Liv Hospital'],
        ['slug' => 'C1-HCHxrNTS', 'ext' => 'webp', 'alt' => 'Operasyon'],
        ['slug' => 'C15C4ovr6OF', 'ext' => 'webp', 'alt' => 'Klinikten'],
        ['slug' => 'C1xQ66kL4TK', 'ext' => 'webp', 'alt' => 'Hasta görüşmesi'],
        ['slug' => 'C1hpvvsC29k', 'ext' => 'webp', 'alt' => 'Ekip'],
        ['slug' => 'C1J5nVkCKnd', 'ext' => 'webp', 'alt' => 'Konsültasyon'],
        ['slug' => 'C0G5VaOCgFu', 'ext' => 'webp', 'alt' => 'Liv Hospital'],
        ['slug' => 'CzoNVlnNyFM', 'ext' => 'webp', 'alt' => 'Klinikten'],
        ['slug' => 'Cznt70kNEtK', 'ext' => 'webp', 'alt' => 'Hasta hikayesi'],
        ['slug' => 'Czlo8RMNQ4K', 'ext' => 'webp', 'alt' => 'Ekip — Prof. Dr. Mustafa Bilge Erdoğan ile'],
        ['slug' => 'CzdRzbBt_wa', 'ext' => 'webp', 'alt' => 'Klinikten anlar'],
        ['slug' => 'CzZl9Gzr178', 'ext' => 'webp', 'alt' => 'Liv Hospital'],
        ['slug' => 'Cy_UnF7tjFS', 'ext' => 'webp', 'alt' => 'Konsültasyon'],
        ['slug' => 'CytFlFrIRUq', 'ext' => 'webp', 'alt' => 'Klinikten'],
        ['slug' => 'CylTtIYK9oK', 'ext' => 'webp', 'alt' => 'Hasta takibi'],
        ['slug' => 'CyV71MzoMRI', 'ext' => 'webp', 'alt' => 'Klinikten'],
        ['slug' => 'CyREdAYoDYN', 'ext' => 'webp', 'alt' => 'Hasta hikayesi'],
        ['slug' => 'CyI7YxSo2Be', 'ext' => 'webp', 'alt' => 'Liv Hospital'],
        ['slug' => 'CyHHfmio69j', 'ext' => 'webp', 'alt' => 'Operasyon'],
        ['slug' => 'Cx3J7rmIOEM', 'ext' => 'webp', 'alt' => 'Klinikten'],
        ['slug' => 'CxxpTdWIAhi', 'ext' => 'webp', 'alt' => 'Hasta görüşmesi'],
        ['slug' => 'CxtRAAcI9sj', 'ext' => 'webp', 'alt' => 'Klinikten'],
        ['slug' => 'Cxa-nHZofT1', 'ext' => 'webp', 'alt' => 'Konsültasyon'],
        ['slug' => 'CxGsSkBovSe', 'ext' => 'webp', 'alt' => 'Klinikten'],
        ['slug' => 'Ce8jGnhDF1F', 'ext' => 'webp', 'alt' => 'Klinikten'],
        ['slug' => 'CUAgauWjcv_', 'ext' => 'jpg',  'alt' => 'Klinikten'],
        ['slug' => 'CMZjmslDIjP', 'ext' => 'jpg',  'alt' => 'Klinikten'],
        ['slug' => 'Bz3DHTVJD3I', 'ext' => 'jpg',  'alt' => 'Klinikten'],
        ['slug' => 'ByUsEVdJngi', 'ext' => 'jpg',  'alt' => 'Şarköy Devlet Hastanesi'],
    ],
];
